config: # cloud
  target: "https://keyc.auth0.com"
  processor: "../__processors__/index.js"
  includeFiles:
    - ../__processors__/cert/certificate.crt
    - ../__processors__/cert/private.key
    - ../.env
  phases:
    - duration: 120
      arrivalRate: 5
      maxVusers: 15
      name: "Warm up load (15 max users)"
  plugins:
    expect: {}
