config: # localhost
  target: "http://localhost:3001"
  processor: "./__processors__/index.js"
  phases:
    - duration: 60
      arrivalRate: 10
      maxVusers: 15
      name: "Warm up load (15 max users)"
  plugins:
    expect: {}
